export const Airports = [
  {
    Id: 144,
    Name: "Abuja International Airport",
    Code: "ABV",
    CountryCode: "NG",
    StateCode: "ABV",
    StateName: "Abuja",
    Latitude: null,
    Longitude: null,
    IsLocal: true,
  },
  {
    Id: 144,
    Name: "Akure Airport",
    Code: "AKR",
    CountryCode: "NG",
    StateCode: "AKR",
    StateName: "Akure",
    Latitude: null,
    Longitude: null,
    IsLocal: true,
  },

  {
    Id: 769,
    Name: "Bauchi Airport",
    Code: "BCU",
    CountryCode: "NG",
    StateCode: "BCU",
    StateName: "Bauchi",
    Latitude: null,
    Longitude: null,
    IsLocal: true,
  },
  {
    Id: 855,
    Name: "Benin City Airport",
    Code: "BNI",
    CountryCode: "NG",
    StateCode: "BNI",
    StateName: "Benin City",
    Latitude: null,
    Longitude: null,
    IsLocal: true,
  },
  {
    Id: 1303,
    Name: "Calabar Airport",
    Code: "CBQ",
    CountryCode: "NG",
    StateCode: "CBQ",
    StateName: "Calabar",
    Latitude: null,
    Longitude: null,
    IsLocal: true,
  },
  {
    Id: 3495,
    Name: "Ibadan Airport",
    Code: "IBA",
    CountryCode: "NG",
    StateCode: "IBA",
    StateName: "Ibadan",
    Latitude: null,
    Longitude: null,
    IsLocal: true,
  },

  {
    Id: 3806,
    Name: "Jos Airport (Yakubu Gowon Airport)",
    Code: "JOS",
    CountryCode: "NG",
    StateCode: "JOS",
    StateName: "Jos",
    Latitude: null,
    Longitude: null,
    IsLocal: true,
  },

  {
    Id: 4004,
    Name: "Katsina Airport",
    Code: "DKA",
    CountryCode: "NG",
    StateCode: "DKA",
    StateName: "Katsina",
    Latitude: null,
    Longitude: null,
    IsLocal: true,
  },

  {
    Id: 4983,
    Name: "Makurdi Airport",
    Code: "MDI",
    CountryCode: "NG",
    StateCode: "MDI",
    StateName: "Makurdi, Benue State",
    Latitude: null,
    Longitude: null,
    IsLocal: true,
  },
  {
    Id: 293,
    Name: "Muritala International Airport",
    Code: "LOS",
    CountryCode: "NG",
    StateCode: "LOS",
    StateName: "Lagos",
    Latitude: null,
    Longitude: null,
    IsLocal: true,
  },

  {
    Id: 6691,
    Name: "Port Harcourt City Airport",
    Code: "PHG",
    CountryCode: "NG",
    StateCode: "PHG",
    StateName: "Port Harcourt City",
    Latitude: null,
    Longitude: null,
    IsLocal: true,
  },
  {
    Id: 8977,
    Name: "Warri Airport",
    Code: "QRW",
    CountryCode: "NG",
    StateCode: "QRW",
    StateName: "Warri",
    Latitude: null,
    Longitude: null,
    IsLocal: true,
  },
];
export const FlightListsDetails = [
  {
    id: 0,
    OperatingAirlineCode: "BA",
    OperatingAirlineName: "British Airways",
    MarketingAirlineCode: "BA",
    MarketingAirlineName: "British Airways",
    Duration: "2h:15m",
    StopOvers: 1,
    HasStopOver: true,
    StopOverDuration: "1h:30m",
    FlightClass: "Premium",
    DepartureDate: "2024-01-20T14:30:00",
    DepartureAirportCode: "LHR",
    DepartureAirportName: "Heathrow Airport",
    DepartureAirportFullName: "Heathrow Airport (LHR)",
    ArrivalDate: "2024-01-20T18:45:00",
    ArrivalAirportCode: "JFK",
    ArrivalAirportName: "John F. Kennedy International Airport",
    ArrivalAirportFullName: "John F. Kennedy International Airport (JFK)",
    TicketFare: 190000.0,
    ServiceCharge: 10000.0,
    TotalFare: 200000.0,
  },
  {
    id: 1,
    OperatingAirlineCode: "TK",
    OperatingAirlineName: "Turkish Airlines",
    MarketingAirlineCode: "TK",
    MarketingAirlineName: "Turkish Airlines",
    Duration: "3h:45m",
    StopOvers: 2,
    HasStopOver: true,
    StopOverDuration: "2h:15m",
    FlightClass: "First",
    DepartureDate: "2024-01-20T13:00:00",
    DepartureAirportCode: "IST",
    DepartureAirportName: "Istanbul Airport",
    DepartureAirportFullName: "Istanbul Airport (IST)",
    ArrivalDate: "2024-01-20T16:45:00",
    ArrivalAirportCode: "SFO",
    ArrivalAirportName: "San Francisco International Airport",
    ArrivalAirportFullName: "San Francisco International Airport (SFO)",
    TicketFare: 290000.0,
    ServiceCharge: 10000.0,
    TotalFare: 300000.0,
  },
  {
    id: 2,
    OperatingAirlineCode: "LH",
    OperatingAirlineName: "Lufthansa",
    MarketingAirlineCode: "LH",
    MarketingAirlineName: "Lufthansa",
    Duration: "1h:30m",
    StopOvers: 0,
    HasStopOver: false,
    StopOverDuration: "0h:00m",
    FlightClass: "Economy",
    DepartureDate: "2024-01-20T10:45:00",
    DepartureAirportCode: "FRA",
    DepartureAirportName: "Frankfurt Airport",
    DepartureAirportFullName: "Frankfurt Airport (FRA)",
    ArrivalDate: "2024-01-20T12:15:00",
    ArrivalAirportCode: "CDG",
    ArrivalAirportName: "Charles de Gaulle Airport",
    ArrivalAirportFullName: "Charles de Gaulle Airport (CDG)",
    TicketFare: 110000.0,
    ServiceCharge: 10000.0,
    TotalFare: 120000.0,
  },
  {
    id: 3,
    OperatingAirlineCode: "SQ",
    OperatingAirlineName: "Singapore Airlines",
    MarketingAirlineCode: "SQ",
    MarketingAirlineName: "Singapore Airlines",
    Duration: "7h:30m",
    StopOvers: 1,
    HasStopOver: true,
    StopOverDuration: "4h:00m",
    FlightClass: "Business",
    DepartureDate: "2024-01-20T08:00:00",
    DepartureAirportCode: "SIN",
    DepartureAirportName: "Changi Airport",
    DepartureAirportFullName: "Changi Airport (SIN)",
    ArrivalDate: "2024-01-20T19:30:00",
    ArrivalAirportCode: "LAX",
    ArrivalAirportName: "Los Angeles International Airport",
    ArrivalAirportFullName: "Los Angeles International Airport (LAX)",
    TicketFare: 240000.0,
    ServiceCharge: 10000.0,
    TotalFare: 250000.0,
  },
  {
    id: 4,
    OperatingAirlineCode: "AF",
    OperatingAirlineName: "Air France",
    MarketingAirlineCode: "AF",
    MarketingAirlineName: "Air France",
    Duration: "1h:45m",
    StopOvers: 0,
    HasStopOver: false,
    StopOverDuration: "0h:00m",
    FlightClass: "Economy",
    DepartureDate: "2024-01-20T20:30:00",
    DepartureAirportCode: "CDG",
    DepartureAirportName: "Charles de Gaulle Airport",
    DepartureAirportFullName: "Charles de Gaulle Airport (CDG)",
    ArrivalDate: "2024-01-20T22:15:00",
    ArrivalAirportCode: "FCO",
    ArrivalAirportName: "Leonardo da Vinci-Fiumicino Airport",
    ArrivalAirportFullName: "Leonardo da Vinci-Fiumicino Airport (FCO)",
    TicketFare: 85000.0,
    ServiceCharge: 10000.0,
    TotalFare: 95000.0,
  },
  {
    id: 5,
    OperatingAirlineCode: "QF",
    OperatingAirlineName: "Qantas",
    MarketingAirlineCode: "QF",
    MarketingAirlineName: "Qantas",
    Duration: "14h:00m",
    StopOvers: 2,
    HasStopOver: true,
    StopOverDuration: "8h:30m",
    FlightClass: "First",
    DepartureDate: "2024-01-20T03:45:00",
    DepartureAirportCode: "SYD",
    DepartureAirportName: "Sydney Airport",
    DepartureAirportFullName: "Sydney Airport (SYD)",
    ArrivalDate: "2024-01-20T18:45:00",
    ArrivalAirportCode: "JFK",
    ArrivalAirportName: "John F. Kennedy International Airport",
    ArrivalAirportFullName: "John F. Kennedy International Airport (JFK)",
    TicketFare: 390000.0,
    ServiceCharge: 10000.0,
    TotalFare: 400000.0,
  },
  {
    id: 6,
    OperatingAirlineCode: "DL",
    OperatingAirlineName: "Delta Airlines",
    MarketingAirlineCode: "DL",
    MarketingAirlineName: "Delta Airlines",
    Duration: "5h:30m",
    StopOvers: 1,
    HasStopOver: true,
    StopOverDuration: "2h:30m",
    FlightClass: "Premium",
    DepartureDate: "2024-01-20T09:30:00",
    DepartureAirportCode: "ATL",
    DepartureAirportName: "Hartsfield-Jackson Atlanta International Airport",
    DepartureAirportFullName:
      "Hartsfield-Jackson Atlanta International Airport (ATL)",
    ArrivalDate: "2024-01-20T15:00:00",
    ArrivalAirportCode: "LAX",
    ArrivalAirportName: "Los Angeles International Airport",
    ArrivalAirportFullName: "Los Angeles International Airport (LAX)",
    TicketFare: 190000.0,
    ServiceCharge: 10000.0,
    TotalFare: 200000.0,
  },
  {
    id: 7,
    OperatingAirlineCode: "UA",
    OperatingAirlineName: "United Airlines",
    MarketingAirlineCode: "UA",
    MarketingAirlineName: "United Airlines",
    Duration: "3h:00m",
    StopOvers: 0,
    HasStopOver: false,
    StopOverDuration: "0h:00m",
    FlightClass: "Economy",
    DepartureDate: "2024-01-20T17:00:00",
    DepartureAirportCode: "ORD",
    DepartureAirportName: "O'Hare International Airport",
    DepartureAirportFullName: "O'Hare International Airport (ORD)",
    ArrivalDate: "2024-01-20T20:00:00",
    ArrivalAirportCode: "LGA",
    ArrivalAirportName: "LaGuardia Airport",
    ArrivalAirportFullName: "LaGuardia Airport (LGA)",
    TicketFare: 80000.0,
    ServiceCharge: 10000,
    TotalFare: 90000.0,
  },
  {
    id: 8,
    OperatingAirlineCode: "EK",
    OperatingAirlineName: "Emirates",
    MarketingAirlineCode: "EK",
    MarketingAirlineName: "Emirates",
    Duration: "4h:00m",
    StopOvers: 1,
    HasStopOver: true,
    StopOverDuration: "2h:00m",
    FlightClass: "First",
    DepartureDate: "2024-01-20T14:00:00",
    DepartureAirportCode: "DXB",
    DepartureAirportName: "Dubai International Airport",
    DepartureAirportFullName: "Dubai International Airport (DXB)",
    ArrivalDate: "2024-01-20T18:00:00",
    ArrivalAirportCode: "JFK",
    ArrivalAirportName: "John F. Kennedy International Airport",
    ArrivalAirportFullName: "John F. Kennedy International Airport (JFK)",
    TicketFare: 320000.0,
    ServiceCharge: 15000.0,
    TotalFare: 335000.0,
  },
  {
    id: 9,
    OperatingAirlineCode: "AA",
    OperatingAirlineName: "American Airlines",
    MarketingAirlineCode: "AA",
    MarketingAirlineName: "American Airlines",
    Duration: "6h:45m",
    StopOvers: 2,
    HasStopOver: true,
    StopOverDuration: "3h:15m",
    FlightClass: "Premium",
    DepartureDate: "2024-01-20T12:30:00",
    DepartureAirportCode: "DFW",
    DepartureAirportName: "Dallas/Fort Worth International Airport",
    DepartureAirportFullName: "Dallas/Fort Worth International Airport (DFW)",
    ArrivalDate: "2024-01-20T19:15:00",
    ArrivalAirportCode: "LGA",
    ArrivalAirportName: "LaGuardia Airport",
    ArrivalAirportFullName: "LaGuardia Airport (LGA)",
    TicketFare: 180000.0,
    ServiceCharge: 12000.0,
    TotalFare: 192000.0,
  },
];
